<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>9469e0f5-d34c-44b5-bb76-0098152e8356</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.9" />
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.*" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9" />
	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	  <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowerShop.Data\FlowerShop.Data.csproj" />
    <ProjectReference Include="..\FlowerShop.Dto\FlowerShop.Dto.csproj" />
  </ItemGroup>

</Project>
